name: merchantgenius-scrape

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - run: npm run merchant
            - name: Commit & Push changes
              uses: actions-js/push@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: main
                force: true