name: top500-scrape

on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://localhost:8083/top500' 