name: upwork-scrape

on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://127.0.0.1:8083/upwork' 