name: upwork-scrape

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 15.x
            - name: Install JS testing dependencies
              run: npm install
            - name: Install Playwright dependencies
              run: npx playwright install-deps
            - name: Install browsers
              run: npx playwright install
            - run: npm run build --if-present
            - run: npm run upwork
            - name: Commit & Push changes
              uses: actions-js/push@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: main
                force: true